"""
Parallel execution coordinator for Level 4 solution generation.

Implements ParallelSolutionGenerationNode from brainstorm_1.md lines 469-482.
Creates execution batches using topological sort and executes them in parallel.
"""

import asyncio
from typing import List, Dict, Any, Set
from ...schemas.state import Level4State, Subproblem, DependencyGraph, Solution, SubproblemStatus
from ...agents.pool import AgentPoolManager
from datetime import datetime


class CircularDependencyError(Exception):
    """Raised when a circular dependency is detected in the subproblem graph."""
    pass


def create_execution_batches(
    subproblems: List[Subproblem],
    dependency_graph: DependencyGraph
) -> List[List[str]]:
    """
    Create batches of subproblems that can be solved in parallel.

    Uses topological sort on dependency graph as described in
    brainstorm_1.md lines 496-518.

    Args:
        subproblems: List of all subproblems
        dependency_graph: Dependency relationships between subproblems

    Returns:
        List of batches, where each batch contains subproblem IDs
        that can be executed in parallel

    Raises:
        CircularDependencyError: If circular dependencies detected
    """
    # Build lookup structures
    subproblem_map = {sp["id"]: sp for sp in subproblems}
    remaining = set(sp["id"] for sp in subproblems)
    solved = set()  # Track solved subproblems

    batches = []

    while remaining:
        # Find subproblems with no unresolved dependencies
        batch = []

        for sp_id in remaining:
            sp = subproblem_map[sp_id]
            dependencies = sp.get("dependencies", [])

            # Check if all dependencies are solved
            all_deps_solved = all(dep_id in solved for dep_id in dependencies)

            if all_deps_solved:
                batch.append(sp_id)

        # If no subproblems can be added to batch, we have circular dependencies
        if not batch:
            raise CircularDependencyError(
                f"Circular dependency detected. Remaining subproblems: {remaining}"
            )

        # Add batch and mark as solved
        batches.append(batch)
        solved.update(batch)
        remaining -= set(batch)

    return batches


async def solve_subproblem(
    subproblem: Subproblem,
    pool_name: str,
    pool_manager: AgentPoolManager
) -> Solution:
    """
    Solve a single subproblem using an agent from the specified pool.

    This is a placeholder that simulates agent execution.
    In production, this would call actual LLM agents.

    Args:
        subproblem: The subproblem to solve
        pool_name: Name of the agent pool to use
        pool_manager: Pool manager instance

    Returns:
        Solution for the subproblem
    """
    start_time = datetime.now()

    # Assign work to agent in pool
    agent = await pool_manager.assign_work_to_pool(pool_name, subproblem["id"])

    if not agent:
        # Pool is full, raise error for retry logic
        raise RuntimeError(f"No available agents in pool {pool_name}")

    try:
        # Simulate LLM call with asyncio.sleep
        # In production, this would be replaced with actual LLM API call
        await asyncio.sleep(0.1)  # Simulate processing time

        # Create mock solution
        solution: Solution = {
            "subproblem_id": subproblem["id"],
            "content": f"Solution for {subproblem['title']}:\n\n"
                      f"Applying {subproblem.get('source_technique', 'general approach')} "
                      f"from {subproblem.get('paradigm', 'general')} paradigm.\n\n"
                      f"[Detailed solution would be generated by LLM here]",
            "reasoning": f"Analyzed the subproblem and applied appropriate techniques "
                        f"based on {subproblem.get('paradigm', 'general')} decomposition.",
            "confidence": 0.85,
            "agent_id": agent.id,
            "agent_pool": pool_name,
            "validation_status": "pending",
            "metadata": {
                "solved_at": datetime.now().isoformat(),
                "technique_used": subproblem.get("source_technique", "general"),
            }
        }

        # Mark task as complete
        response_time = (datetime.now() - start_time).total_seconds()
        pool_manager.complete_task(agent.id, response_time)

        return solution

    except Exception as e:
        # Mark task as failed
        pool_manager.fail_task(agent.id)
        raise RuntimeError(f"Failed to solve subproblem {subproblem['id']}: {str(e)}")


async def execute_batch(
    batch: List[str],
    subproblem_map: Dict[str, Subproblem],
    agent_assignments: Dict[str, str],
    pool_manager: AgentPoolManager,
    progress_callback: Any = None
) -> Dict[str, Solution]:
    """
    Execute a batch of subproblems in parallel.

    Args:
        batch: List of subproblem IDs to execute
        subproblem_map: Mapping of subproblem ID to subproblem
        agent_assignments: Mapping of subproblem ID to pool name
        pool_manager: Pool manager instance
        progress_callback: Optional callback for progress updates

    Returns:
        Dictionary mapping subproblem ID to solution
    """
    tasks = []

    for sp_id in batch:
        subproblem = subproblem_map[sp_id]
        pool_name = agent_assignments.get(sp_id, "general_pool")

        # Create async task for this subproblem
        task = solve_subproblem(subproblem, pool_name, pool_manager)
        tasks.append((sp_id, task))

    # Execute all tasks in parallel
    results = {}
    for sp_id, task in tasks:
        try:
            solution = await task
            results[sp_id] = solution

            # Call progress callback if provided
            if progress_callback:
                progress_callback(sp_id, "completed", solution)

        except Exception as e:
            # Log failure but continue with other tasks
            if progress_callback:
                progress_callback(sp_id, "failed", str(e))

    return results


async def execute_parallel_solutions(state: Level4State) -> Level4State:
    """
    Node function: Execute all subproblems in parallel batches.

    Implements ParallelSolutionGenerationNode from brainstorm_1.md lines 469-482.

    Creates batches using topological sort, then executes each batch in parallel,
    waiting for completion before moving to next batch.

    Args:
        state: Level4State with routing decisions and agent assignments

    Returns:
        Updated state with partial_solutions and failed_subproblems
    """
    subproblems = state.get("integrated_subproblems", [])
    dependency_graph = state.get("subproblem_dependencies", {"nodes": [], "edges": []})
    agent_assignments = state.get("agent_assignments", {})

    if not subproblems:
        return {
            **state,
            "execution_batches": [],
            "partial_solutions": {},
            "failed_subproblems": [],
        }

    # Create execution batches
    try:
        batches = create_execution_batches(subproblems, dependency_graph)
    except CircularDependencyError as e:
        # Handle circular dependencies
        return {
            **state,
            "execution_batches": [],
            "partial_solutions": {},
            "failed_subproblems": [sp["id"] for sp in subproblems],
            "progress_tracking": {
                "status": "failed",
                "error": str(e),
            }
        }

    # Initialize pool manager
    pool_manager = AgentPoolManager()

    # Create subproblem lookup
    subproblem_map = {sp["id"]: sp for sp in subproblems}

    # Track results
    all_solutions = {}
    failed_subproblems = []

    # Progress tracking
    progress_tracking = {
        "total_batches": len(batches),
        "completed_batches": 0,
        "total_subproblems": len(subproblems),
        "completed_subproblems": 0,
        "failed_subproblems": 0,
        "started_at": datetime.now().isoformat(),
    }

    def progress_callback(sp_id: str, status: str, result: Any):
        """Callback to update progress tracking."""
        if status == "completed":
            progress_tracking["completed_subproblems"] += 1
        elif status == "failed":
            progress_tracking["failed_subproblems"] += 1
            failed_subproblems.append(sp_id)

    # Execute batches sequentially (but subproblems within batch are parallel)
    for batch_idx, batch in enumerate(batches):
        batch_solutions = await execute_batch(
            batch,
            subproblem_map,
            agent_assignments,
            pool_manager,
            progress_callback
        )

        # Merge batch solutions into all solutions
        all_solutions.update(batch_solutions)

        # Update progress
        progress_tracking["completed_batches"] = batch_idx + 1

    # Finalize progress tracking
    progress_tracking["completed_at"] = datetime.now().isoformat()
    progress_tracking["status"] = "completed" if not failed_subproblems else "partial"

    return {
        **state,
        "execution_batches": batches,
        "partial_solutions": all_solutions,
        "failed_subproblems": failed_subproblems,
        "progress_tracking": progress_tracking,
        "agent_pool_status": pool_manager.get_all_pool_statuses(),
    }
